##服务器端口号
#server.port=8080
#
##数据库
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/educationalmanagementsystem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#spring.datasource.username=root
#spring.datasource.password=123456
#
#spring.mvc.view.suffix=.jsp
#spring.mvc.view.prefix=/WEB-INF/pages/
#
#mybatis.mapper-locations=classpath:com/fc/mapper/*.xml




spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/educationalmanagementsystem?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimeZone=GTM+8
    username: root
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
mybatis:
  # mybatis-config.xml配置文件所在的路径
  #  config-location:
  # 扫描指定路径下的映射文件（sql）
  mapper-locations: classpath:com/fc/mapper/*.xml
  configuration:
    # 加sql执行日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 二级缓存
    cache-enabled: true
    # 主键回填
    use-generated-keys: true
    # 驼峰映射
    map-underscore-to-camel-case: true
    # 懒加载
    lazy-loading-enabled: true
    # 积极加载
    aggressive-lazy-loading: false
  # 别名所在的包
  type-aliases-package: com.fc.entity
# 分页插件
pagehelper:
  reasonable: true
  auto-dialect: true

